version: "3.8"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobsdb
    ports:
      - "5434:5434"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/jobsdb
    depends_on:
      - db
volumes:
  pgdata:
